### ISSUE TITLE
python的属性设置 | 小胖鱼@Think

### ISSUE THREAD

**Issue by yuzhiquan** [yuzhiquan/yuzhiquan.github.io#2]
https://yuzhiquan.github.io/2016/11/22/python_setattr/

**Comment by yuzhiquan** [comment]
测试gitment

**Comment by CaoChunfang** [comment]
作者，你好！你是作为Cas5.1对接SAP的单点系统吗？我看了你上面的博文有几个问题想问一下。1、要把证书引入到java环境中？？？这是引入的cas自动生成的那个证书吗？2、service配置中的serviceId不应该是SP也就是SAP那边的那个地址吗？怎么你说是metadata文件中的entityId呢，这个entityId不是application.properties配置文件中的cas.authn.samlIdp.entityId，那这个应该idp的地址也就是咱们cas这边的地址吧？还希望作者不吝赐教，非常感谢！

**Comment by yuzhiquan** [comment]
@CaoChunfang  
- 证书是`cas`系统要用的域名的证书，一般是买的，也可以自己签署，不是`cas`自动生成的那个
- `serviceid`是`sp`那边提供的`spmetadata`里面的`entityID`字段，跟配置文件里的`cas.authn.samlIdp.entityId`这个字段**没有关系**，因为这个时候已经是在跟`sp`进行认证交互了

**Comment by CaoChunfang** [comment]
哦哦哦好的，谢谢。我是自己签发的证书，用JDK里面的keytool签发的证书，暂时用着。我还想请教一点东西。CAS跟SAP（你这里的SAP是不是指的国外的那个专门做oa、erp等系统的厂商啊）系统进行交互的时候是通过/idp/profile/SAML2/POST/SSO和/idp/profile/SAML2/POST/SLO请求，可我突然想到那我CAS这边登录页面的用户名密码验证是用哪个请求啊？直接都懵逼了。我这边是普通的cas方式和SAML2.0共存的情况。那么这个登录操作还是跟普通的cas请求一样用/login?service=&username=&password=&lt=&rememberMe=   请求去传验证用户名密码吗？这个SAML2.0是不是只是相当于把普通的cas里面的票据验证换成了通过SAML2.0的协议这样啊。不知道作者是否方便加一下我的QQ(4780665)，想找你帮帮忙解一下惑。谢谢了！

**Comment by yuzhiquan** [comment]
@CaoChunfang 
对`java`不怎么熟悉，也没用`cas`这个协议做单点，不过在`CAS`单点认证服务器下发的`idp-metadata`里会看到一些`location`,比如`https://cas.example.org/idp/profile/SAML2/POST/SSO`,这个应该专用于`saml2`协议的，客服端会带着指定格式的数据来访问这个`url`，然后就交互进行认证，认证之后信任客户端后会到最后的登录页面，所以`cas`协议的话可能也有类似的，不太确定，需要研究下`cas`协议，但是他们用的登录验证`url`应该是不一样的，但登录页面是一致的。
不知道你要用什么语言来写`cas`认证，我知道`python`有直接封装好的`sdk`可以进行认证……

**Comment by CaoChunfang** [comment]
哦哦，好的，谢谢作者。我是用java写的。那行，那我再研究一下！

**Comment by CaoChunfang** [comment]
作者 我又来了，嘻嘻。有个不情之请，能给我看一下你们的cas的application.properties有关SAML2.0的部分是怎么配置的吗？多谢。感觉用这个cas的实在太少了，特别是5.1以上版本的。纠结。

**Comment by yuzhiquan** [comment]
@CaoChunfang 
这篇文章[CAS5.x编译、部署(1)-LDAP支持](https://yuzhiquan.github.io/2017/05/03/CAS-compile-plugin/)里写了`SAML idp`相关的配置
